import "./css/globals.css";
import type { Metadata } from "next";
import { TheHeader } from "./components/TheHeader";
import { TheNavPanel } from "./components/TheNavPanel";

export const metadata: Metadata = {
  title: "Todo List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="wrapper">
      <TheHeader />
          <main>
            <TheNavPanel />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
